import {
  FaCar,
  FaCarSide,
  FaTruck,
  FaMotorcycle,
  FaTaxi,
  FaTruckMoving,
  FaHardHat,
  FaBolt,
  FaIndustry,
  FaHandHoldingUsd,
  FaParking,
  FaCode,
  FaMobileAlt,
  FaGlobe,
  FaCloud,
  FaShieldAlt,
  FaRobot,
  FaUserTie,
  FaUserShield,
  FaBalanceScale,
  FaHeadset,
  FaMapMarkerAlt,
  FaTruckPickup,
  FaFileAlt,
  FaTools,
  FaWarehouse,
  FaPhoneAlt,
  FaTractor,
  FaFileContract,
  FaChartLine,
} from 'react-icons/fa';

const iconMap = {
  FaCar,
  FaCarSide,
  FaTruck,
  FaMotorcycle,
  FaTaxi,
  FaTruckMoving,
  FaHardHat,
  FaBolt,
  FaIndustry,
  FaHandHoldingUsd,
  FaParking,
  FaCode,
  FaMobileAlt,
  FaGlobe,
  FaCloud,
  FaShieldAlt,
  FaRobot,
  FaUserTie,
  FaUserShield,
  FaBalanceScale,
  FaHeadset,
  FaMapMarkerAlt,
  FaTruckPickup,
  FaFileAlt,
  FaTools,
  FaWarehouse,
  FaPhoneAlt,
  FaTractor,
  FaFileContract,
  FaChartLine,
};

export const getIcon = (name, fallback = FaCar) => iconMap[name] || fallback;
